### ISSUE TITLE
centeredSlides: false, show direct last slide in directive approach

### ISSUE THREAD

**Issue by muhammadali208** [zefoy/ngx-swiper-wrapper#100]
when i change the centerSlides property true to false. then slider show last slide direct in directive approach. your solution will be worthy for me

**Comment by sconix** [comment]
Not completely sure what you mean, but you should create a Plunker example of the problem. Or at least share some code (config, template etc.).

**Comment by muhammadali208** [comment]
i resolve the above error by setting index 0 in init function.
now i am getting error like: i want to add slides dynamically when i get in event callback from reachEnd. i want push slides in the existing slides. but when i add nothing happend. 

  public reachAtEnd() {
    this.directiveRef['instance'].isEnd = false;
    this.slides = this.slides.concat(this.slidesArr);
    this.directiveRef.setIndex(this.directiveRef['instance'].activeIndex+ 1);
  }
 what should i do to get the desire functionality.

**Comment by sconix** [comment]
You need to call update function manually when ever elements changes dynamically or use observer: true in the swiper config.

**Comment by sconix** [comment]
I now believe that your original issue is the same than in #103. Which is a Swiper bug and can be go around with using manually calling update when slides are rendered and not using observer: true.

I have reported the issue to Swiper, until its fixed manual usage of update call might be needed instead of observer true.
