### ISSUE TITLE
did not work proper multiple directive based swiper in one component.

### ISSUE THREAD

**Issue by muhammadali208** [zefoy/ngx-swiper-wrapper#110]
my purpose is to run the directive based multiple swiper in one component. but the issue i facing is transition is not working, directive1 swiper is not working and i have to add <swiper> </swiper> tag in html to run the directive based swiper.

here is my plkr example:

https://plnkr.co/edit/9Ou5FqvOEVdxl3WzGfm0?p=preview

your solution will be a kind gesture.

**Comment by sconix** [comment]
I am not 100% sure what you are trying to say, but I guess its about the ViewChild references since at least those you have set wrong. ViewChild fetches the reference to a *first* element that matches the type (in this case SwiperDirective). So you need to use component names (ViewChild('swiperDirective1') or ViewChildren.

**Comment by muhammadali208** [comment]
i resolve some issues but now i want to put the navigation arrows outside the slider?
https://plnkr.co/edit/9Ou5FqvOEVdxl3WzGfm0?p=preview

**Comment by sconix** [comment]
For that you would need to seek assistance elsewhere, all I can say is that normal css styling is needed. If I had time I would gladly help, but sadly I don't so therefore I keep git issues only for reporting issues and not for support (specially not for general Angular / CSS related support).
