### ISSUE TITLE
(click) listener doesn't work on last slide and after loop

### ISSUE THREAD

**Issue by masives** [zefoy/ngx-swiper-wrapper#123]
Hi,

On the images I use inside slide I use click listener that forces modal to be shown. However the problem is that on the last slide and first after loop the click event isn't registered.

I saw the thread on ion-slides but it didn't work for me [#12098](https://github.com/ionic-team/ionic/issues/12098)

Is there any way I can workaround this?

sample code:
```
<swiper class="swiper-container" [config]="config">
        <div *ngFor="let slide of slides" class="swiper-slide">
            <div class="slider-wrapper">
                <div class="slide">
                    <div class="portfolio-item-tint"  (click)="openModal(slide.link)" ></div>
                </div>
                <h2 class="portfolio-item-title">{{slide.title}}</h2>
            </div>
        </div>
      </swiper>
```

config:
```
    direction: 'horizontal',
    slidesPerView: 3,
    keyboard: true,
    mousewheel: false,
    scrollbar: false,
    navigation: true,
    pagination: false,
    loop: true,
    autoplay: true,
    centeredSlides: true,
    preventClicks: false,
    preventClicksPropagation: false
```

**Comment by sconix** [comment]
I don't see why the workaround described would not work. The problem is that Swiper makes copies of the slides where you obviously will loose the event handlers for those slides. So the click listener has to be in the swiper component and you just need to check if the event target was what you are interested of. The click event is naturally always propagated since its a normal DOM event and the slide copying can not have an effect for that.

**Comment by masives** [comment]
Thank you for explanation I'll try it again with that in mind
