### ISSUE TITLE
Swiper v5.3.3 update() bug

### ISSUE THREAD

**Issue by gitdisrupt** [zefoy/ngx-swiper-wrapper#126]
What were the swiper initialization bugs that you fixed?

Because now i am seeing a problem with the` .update()` method.

It does not seem to be updating my swiper instance correctly on init anymore whereas version `5.3.2` is OK and works as expected.

to be specific ... on init i save a reference to the swiper:
`this.playlistSwiper = this.playlistSwiperRef.swiper();`

When the swiper first displays, the sizing for each image in my swiper does not display correctly until i call the `.update()` method on the swiper instance, which corrects the display, like so:

`this.playlistSwiper.update();`

In version `5.3.2` this works OK. Your latest release `5.3.3` seems to break it. There are no errors firing, but the swiper display does not correct itself. I have tried using SetTimeouts, ngZone etc ... nothing works to solve it.

**Comment by sconix** [comment]
If Swiper is initialized in ngOnInit then bunch of the options like loop etc. wont work on the initial rendering. So that was fixed by switching to doing the initialization after the view is initialized which is anyway the proper phase to do it when dealing with pure JS libraries which relay on DOM.

It should not have any effect on the update functionality. What are you refering to when you speak about on init? To ngOnInit phase or something else?

**Comment by gitdisrupt** [comment]
Right, i understand what you said, that makes sense.

I am not using the ngOnInit function.

i load the swiper module into my components module:
`import { SwiperModule } from 'ngx-swiper-wrapper';`

And then in the component template, i use an `*ngIf` attribute to init the swiper instance once data becomes available via an observable.

Here is the opening div tag:

<div #playlistSwiperRef="ngxSwiper" class="swiper-container"
        [swiper]="config" [index]="startIndex" *ngIf="enablePlaylist" [hidden]="!displayPlaylist"
        (indexChange)="updateIndex($event)"
        (reachEnd)="swiperEvent({data:'reachEnd'})"
        (reachBeginning)="swiperEvent({data:'reachBeginning'})">

When the observable returns data:

first i set a boolean titled `enablePlaylist` to `true` which initiates the display of the swiper instance.

Then in my component, i set a reference to it: `this.playlistSwiper = this.playlistSwiperRef.swiper();`

When the content loads into the swiper, the images are not sized correctly, so i trigger an update using the update method like so: `this.playlistSwiper.update();`

With version 5.3.2 this works without issue. The images instantly display correctly as expected.

With version 5.3.3, the update does not seem to fire. The images do not get resized. Nor does the size of the swiper slide. No errors appear in the console. So i am not sure how to troubleshoot without digging into your code.

Any help greatly appreciated.

**Comment by gitdisrupt** [comment]
I should add ... i am monitoring my observable from the ngOnInit function like so:
```
ngOnInit() {
    this.playlistSubscribe = this.globalService.playlistState$.subscribe(value => this.playlistUpdate(value));
}
```
Should i set that subscription in the  `AfterViewInit` method instead?

**Comment by sconix** [comment]
Good that you got your issue resolved, I think I should have done a minor version bump instead a patch bump for this change since I now realized that some users might need to update the code if they were relaying on ngOnInit. Anyway the change had to be done to have more consistent end result with different Swiper options.
