### ISSUE TITLE
Change speed value after configuration

### ISSUE THREAD

**Issue by laclac777** [zefoy/ngx-swiper-wrapper#133]
I tried to implement a solution where the navigator button double click sets SwiperRef.config.speed 2x and a debounce sets back the original value. It seems I can set this speed value only inside of the S_TRANSITIONEND event which is not enough. Have you any idea at where else can I change this configuration?

**Comment by sconix** [comment]
When ever you change the wrapper configuration Swiper is re-initialized (re-created). So that limits the config options that you can change and when. There naturally is no rule book for the settings / change options its just something you need to experiment with. 

The other option is to change the config directly to the Swiper instance which I think you are trying to do. I have no idea what config options you can change on the fly if any, I am not that familiar with Swiper implementation and its architecture. So for that you need to direct the question to the Swiper repository.

**Comment by laclac777** [comment]
Your answer gave me breakthrough. Setting directly to the Swiper instance do the job. Thx.
