### ISSUE TITLE
Swiper v4 Typings

### ISSUE THREAD

**Issue by odahcam** [zefoy/ngx-swiper-wrapper#136]
I'm building some Swiper 4.1 typings, I would like to know if this would be usefull here or/and you could help me on get them done. 

Here's the Swiper typings I'm working on: https://github.com/odahcam/DefinitelyTyped/tree/master/types/swiper

Thanks.

**Comment by sconix** [comment]
Sure I would include the typings if they would be available so they would be useful. Sadly I don't have time to help to get them done since at the moment I am super busy since we are in the final phases of getting our product out so my time limited off work coding stuff is pretty much zero.

Anyway thanks for letting me know that such typing are in process of being done.
