### ISSUE TITLE
Bug with `loop=true` and more than 1 item per view

### ISSUE THREAD

**Issue by brunolm** [zefoy/ngx-swiper-wrapper#138]
Demo: https://stackblitz.com/edit/github-ph1huz

- `loop` = `true`
- `itemsPerView` = `3`

Click `itemsPerView` (3) times up.

Expected
To see an element previous to the current one

Actual
No elements are shown previous to the current one

**Comment by sconix** [comment]
This is just a wrapper for Swiper so any bugs related to the Swiper does not concern this library. Maintainer of Swiper has been ignoring any problems related to using Swiper with Angular so I would not expect much help by reporting the problem for Swiper. Most issues are due to the async nature of Angular and many problems can be fixed by either making sure that the dom is fully ready before initializing Swiper or by calling update manually once the dom is ready.
