### ISSUE TITLE
SSR slide width

### ISSUE THREAD

**Issue by AN602** [zefoy/ngx-swiper-wrapper#161]
I´m currently trying to make this swiper work with SSR in Angular 6.
There is heavy flickering on the initial page load since the slide widths are not set by the directive while being run on the server side.
My current workaround is to set a similar slide width in my CSS and let Swiper override the styling after initialization on the client side.
This workaround is time consuming, if you have multiple Swipers with different breakpoints, and not perfect so I wanted to ask if there is some other way to solve this?

**Comment by sconix** [comment]
When using SSR the Swiper is not initialized at all since it does not support SSR. So what you are doing is pretty much the only thing you can do. I know that Swiper 4 did get some SSR support at some point, but at least in the beginning it still was not working and I have not had time to test it myself that what is its current condition that could the initializing of the Swiper be now allowed even in SSR. So in other words you could try removing the the platform check from this directive to see if the Swiper works.

**Comment by DmitriyIvchenko** [comment]
I already use it with SSR, it works good

**Comment by AN602** [comment]
Sorry for the late response. I´ve tried to disable your platform check. It seems that swiper now checks if the window variable is defined to catch SSR related exceptions. There also seems to be a swiper ES module which uses a project called 'ssr-window'. I´m currently not quiet sure what it´s for and didn´t have time to rewrite your code to use this module. Maybe I can look into it in the future. The swiper docs are really sparse regarding SSR.
