### ISSUE TITLE
Css z-index is breaking by ngx-swiper(Angular)

### ISSUE THREAD

**Issue by sahilkatia** [zefoy/ngx-swiper-wrapper#186]
I am using ng-swiper, for slide in phones views. I have one popup which have z-index property and its inside swiper tags. But swiper tags disturbs its z-index property. I am sharing stackblitz link for that

[https://stackblitz.com/edit/swipper-pagination?](url)

If I am using same popup code under div without swiper tags then z-index of popup wokrs fine

**Comment by sahilkatia** [comment]
@sconix  Its nothing to do with encapsulation. I tried with overflow property, which makes it work but also showing me in-active slide

`   <style>
      swiper > .swiper.s-wrapper .swiper-wrapper .swiper-slide,
      .swiper-container,
      .horizontal-container > .action-container {
        overflow: visible;
      }
    
    </style>`

This code I added in index.html, it works but again showing inactive slide too

**Comment by sconix** [comment]
Sorry I did not check the example just read that issue about z-index, but now I see that the issue has nothing to do with z-index.

Thats how CSS works, you cannot have child element popping out of overflow hidden parent. Thats just a basic limitation of CSS. And you can not change the overflow since its needed for Swiper to work as you have seen.

Normally in web apps you place popup elements into body or common overlay element and position them with JS. You can look into using material cdk or some other libraries for that etc. So this question is more of an generic web development issue and not related to this library.

**Comment by sahilkatia** [comment]
@sconix  I am trying to make it work since yesterday, i would appreciate if you can provide me some useful links

**Comment by sahilkatia** [comment]
@sconix  I tried to it with overlay properties but no luck

**Comment by sahilkatia** [comment]
https://stackblitz.com/edit/swipper-pagination-uq2cxp?file=src%2Fapp%2Fapp.component.css
seems like swiper hides everything

**Comment by sconix** [comment]
Well I already told how to do it in web apps. Popup can not be placed under Swiper that just won't work. Those are the limitations of HTML/CSS engines. Popups are therefore always placed under the root i.e. body element and usually withing special overlay component. There are libs that help with that such as the material cdk library that provides helpers for implementing popups that work with every component. So this is question about normal web development so you might get more luck with general help forums like Stackoverflow.
