### ISSUE TITLE
Pagination settings are not applyable. Customised pagination settings are always hidden.

### ISSUE THREAD

**Issue by Omi0** [zefoy/ngx-swiper-wrapper#194]
Because SwiperConfigInterface defines pagination as 
`pagination?: boolean | SwiperPaginationInterface;`
but pagination are hidden if
`swiperConfig?.pagination !== true`
You can't specify pagination settings as an object:
```
pagination: {
  clickable: true
}

```
because it will be always hidden. Need to change the line 11 from 
```
<div class="swiper-pagination" [hidden]="swiperConfig?.pagination !== true && swiperConfig?.pagination?.el !== '.swiper-pagination'" (click)="onPaginationClick($event.target.getAttribute('index'))" (keyup.enter)="onPaginationClick($event.target.getAttribute('index'))"></div>
```
to 

```
<div class="swiper-pagination" [hidden]="!swiperConfig?.pagination || swiperConfig?.pagination?.el !== '.swiper-pagination'" (click)="onPaginationClick($event.target.getAttribute('index'))" (keyup.enter)="onPaginationClick($event.target.getAttribute('index'))"></div>

```
https://github.com/zefoy/ngx-swiper-wrapper/blob/3bc1c2da4a9946354394a6e3a5d06f7c9a3c998a/src/lib/swiper.component.html#L11

**Comment by sconix** [comment]
Well the idea has been that the pagination is only shown for default configuration. When you provide pagination configuration you most likely are wanting to use custom pagination as well. Since setting pagination true will give you clickable pagination.

So you can just use pagination true or just set the el configuration to default as well in your pagination configuration. 

You are also correct that I could improve the hidden conditions to make the usage bit easier. So I might do that for next release.

**Comment by sconix** [comment]
I changed the showing rules for the upcoming release so they will be more developer friendly now.
