### ISSUE TITLE
Autoheight recalculation doesn't work

### ISSUE THREAD

**Issue by Triplecorpse** [zefoy/ngx-swiper-wrapper#201]
Hello again. I doubted whether to reopen the old issue [How to recalculate the height?](https://github.com/zefoy/ngx-swiper-wrapper/issues/200) or to open a new one.

This time the question is kinda different so I decided to open a new one.

What I want to achieve is to set autoHeight on each slide as I made on [JSFiddle](https://jsfiddle.net/g4s7j2t1/7/). The updateAutoHeight() method didn't work so I need to ask once more.

I copied all the settings from my app but it seems that original swiper behaves in different way than yours. I have even updated yours to `7.1.1` but it took no effect. Earlier I had `6.4.0`

As you see, it was sufficient to set an option `autoHeight: true` in jsFiddle. In my app a scrollbar appears and I can scroll the picture but the height of a swiper remains the same. I have commented all my stylesheet in case of my styles override the behaviour but this was not the reason.

You can watch the result with your wrapper on the page [http://romanenkova-staging.herokuapp.com/en/about](http://romanenkova-staging.herokuapp.com/en/about). For the first time it could open for a long time because of free server goes in stand-by mode after 30 mins of inactivity.

If you go to my page from mobile device, you could see a reason why autoHeight is extremely vital for me.

And yes, the expected behaviour is as on [JSFiddle](https://jsfiddle.net/g4s7j2t1/7/) on original swiper.

**Comment by sconix** [comment]
The most likely reason is the dynamic nature or the Angular is the fault. Swiper has never been designed to be used with Angular and its really hard to try to work around those issues within this wrapper.

Often using observer: true in the config helps with some dynamic issues, but sometimes calling update for the Swiper is needed for example in ngAfterViewInit or when the slides has been rendered. So using those can help, but not sure if they help with your problem. 

Atm I do not have time to look into this more deeply that can there be something that I could do in the wrapper to avoid this or if it can be something in this lib that is causing this. Most likely its not caused by this lib since I have tried my best to make directive behave exactly like using the native Swiper (only the component has some additions to the native Swiper). So specially when using the directive way there should not be any difference to native Swiper only what challenges the Angular brings for the Swiper.

So first I would try to use the observer config and also try calling he update for example within some timeout just to see if they help at all.

**Comment by Triplecorpse** [comment]
Thank you. I made this by some events and manipulating dom directly. Donn’t think it is a good practice but it works.
