### ISSUE TITLE
Angular 7 support - SASS error

### ISSUE THREAD

**Issue by oldbasilbear** [zefoy/ngx-swiper-wrapper#214]
I am upgrading from ng5 to ng7, but my attempt to  `ng build --prod` has reported an error:

> ERROR in Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
       ^
      Invalid CSS after "import {": expected "}", was "$, addClass, remove"
      in /home/victor/src/sabre/sabre-desktop/node_modules/swiper/dist/js/swiper.esm.bundle.js (line 13, column 9)

I am in need of some guidance as to what to do to overcome this and build my project.

**Comment by oldbasilbear** [comment]
Hi folks - has anyone got some help to offer on this matter, please?

**Comment by sconix** [comment]
You might want to ask some general help forums since that is not related to this library instead its matter of your build configuration. So you might get better luck in forums that are related to the build system you are using. For some reason your build setup does not know how to handle esm module loading so its most likely miss configured or that you need some special configuration.
