### ISSUE TITLE
hashnavWatchState make swiper crazy 

### ISSUE THREAD

**Issue by metazoa-org** [zefoy/ngx-swiper-wrapper#22]
When hashnavWatchState + hashnav are set to true,  swiper return to first one after each interaction

**Comment by sconix** [comment]
I'll check if its something thats because of this library or Swiper itself.

**Comment by sconix** [comment]
I tried those configuration options in the example app and it works perfectly, so can you give me an Plunker example or something that when it does not work?

**Comment by saadaorg** [comment]
I was having the same problem. I realized this was because I was using the data-history attribute to set the slide url (as seems to be indicated in the documentation). But the hash navigation example (https://github.com/nolimits4web/Swiper/blob/master/demos/25-hash-navigation.html) shows that the data-hash attribute should be used. This fixes the issue.

**Comment by sconix** [comment]
Ok, good to know. I was also using the data-hash so thats why I could not reproduce this.
