### ISSUE TITLE
Migration notes

### ISSUE THREAD

**Issue by almothafar** [zefoy/ngx-swiper-wrapper#43]
Thank you for your efforts, but I would like to push migration notes when you do breaking changes, last updates contains breaking changes and I'm just wasting time to know what the changes were done and how to migrate, please put some notes about migration steps for later releases.

**Comment by sconix** [comment]
Sorry, but I didn't have time to do complete migration notes since for this release they are bit difficult to make since the whole structure changed. So there isn't any simple way to describe the changes needed. But this restructuring was necessary for the maintainability of the code so that there are no duplicate code for the directive and component.

The only breaking changes should be styling as said in the release notes. But what and how to change its rather hard to say.

**Comment by picosam** [comment]
Hello, but does this mean that I cannot use the component anymore? In other words, I have to use it in directive mode only?

**Comment by sconix** [comment]
No the component is still available it just uses the directive internally instead of duplicating the code.

**Comment by picosam** [comment]
Thank you. Is it possible to just mention the style classes that will break so I may update them? I assume I will simply have to change the names?

**Comment by sconix** [comment]
There is no changes to the class names, the structure of the component has changed slightly (there is an extra div due to the angular not supporting host directives).  So in most cases there is no breaking changes and its impossible to list them if there are. It depends how you have defined your styles if they are loosely defined then there should not be need for changes. 

The problem that issue reporter had was most likely due to the previous version having a bug so it just happened to work with that version even it should not have. He was using the component with custom elements and there might be some issues in such use cases. In any case in those situation its better to use the directive since there is no point using component if you are going to provide custom elements by yourself. The only difference between the component and directive is that component provides the default elements (pagination etc.) so you don't need to define them in your template.
