### ISSUE TITLE
isAtFirst and isAtLast not setting up

### ISSUE THREAD

**Issue by Clipperer** [zefoy/ngx-swiper-wrapper#45]
Hey,

Looks like the component is missing those two properties in the new version. They are available but not set, and the isBeginning and isEnd in the swiper object of the directiveRef are not accessible. Any thoughts on that?

**Comment by sconix** [comment]
At least they are set in the example app component (they are used for the next/prev button disabled styling). Are you sure you have the latest version (4.5.4)? Since there was a bug with those not being set earlier, but now they should be fine. If not then can you tell me how you change the slide so I could try to replicate it with the example app.

**Comment by Clipperer** [comment]
Thanks for the speedy reply. The version is the current one, I am using the slideNext and slidePrev methods of the directiveRef, and they are working fine, here's a console dump of the ViewChild object on slide change event (which is working perfectly fine)
![image](https://user-images.githubusercontent.com/8537212/28868513-fde35efe-7779-11e7-93fe-8be684176899.png)

**Comment by sconix** [comment]
Ok let me look into this bit more closely. So are you using the slideChangeStart event? Or are you providing onSlideChangeStart callback in the configuration? Since the component registers to that event to keep up with the state, but I though that multiple event listeners is allowed by the swiper so it should still work even if you use those but might be what causes the bug.

**Comment by Clipperer** [comment]
I am using the methods in the component config. isBeginning actually works, but isEnd always returns false, I guess it could be linked to the fact that the content of the swiper is dynamic (using ngFor on some parts), but it was working fine until recently.

Thanks again for the assistance, I do hope that the discussion is valuable for the module, which is great btw.

**Comment by sconix** [comment]
The previous version used a small hack to keep the isAtLast/Beginning in sync, so could be that the current way doing things is not yet full prove. I try to replicate the problem somehow so I could see what is the proper fix.

**Comment by Clipperer** [comment]
Got a little update, might be the fix:
swiper.directive.js
        options.onSlideChangeStart = function (swiper) {
            if (onSlideChangeStart) {
                onSlideChangeStart(swiper);
            }
            _this.zone.run(function () {
              _this.indexChange.emit(swiper.snapIndex);
            });
        };
  _this.indexChange.emit(swiper.snapIndex); should be just _this.indexChange.emit(swiper);
because in swiper.component.js:129 onIndexUpdate expects a swiper object and not an index of the changed slide.

**Comment by sconix** [comment]
Ah true i have forgot to update the component event handler. Thanks for the info, I did not have time to look into this yet so this saves time. I will make a new release tomorrow.

**Comment by sconix** [comment]
I will soon release 4.6.0 in which the isAtLast and isAtFirst has bit more elegant implementation and they should now actually work :).
