### ISSUE TITLE
Change the pagination style

### ISSUE THREAD

**Issue by Ajauregui69** [zefoy/ngx-swiper-wrapper#55]
Is it possible to change the size and the color of the paggination bullets??

**Comment by sconix** [comment]
Sure with CSS you can style anything.

**Comment by Ajauregui69** [comment]
i already try that with the class .swiper-pagination-bullet and nothing happened

**Comment by sconix** [comment]
All I can say that there are no special tricks needed. Normal Angular styling rules apply. The component uses custom pagination renderer so that the actual bullet class is actually swiper-pagination-handle which is wrapped inside the swiper-pagination-bullet class. Of course that you can easily see from developer console with the inspector.

**Comment by Ajauregui69** [comment]
Is there any example that you could show me, please??

**Comment by sconix** [comment]
Not sure what example would help if you are new to Angular. You need to look into Angular style encapsulation and how to style elements inside components.

**Comment by thienedits** [comment]
Yes Its not working for me as well. I am using styleUrls in component definition and added the class and it did nothing

````
.swiper-pagination-bullet {
    background: #fff;
    opacity: .6;
}
````

**Comment by thienedits** [comment]
Ok i had to turn on  `encapsulation:ViewEncapsulation.None` in component definition and now it works

**Comment by miroamarillo** [comment]
encapsulation:ViewEncapsulation.None breaks the whole layout of the swiper for me.  Anyone?
